# Generated by Django 4.0.2 on 2022-04-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_newpost_date_newpost_likes_newpost_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
