# Generated by Django 4.0.2 on 2022-04-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_userpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpage',
            name='followed',
            field=models.BooleanField(default=False),
        ),
    ]
