# Generated by Django 4.0.2 on 2022-05-03 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='user_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='network.userpage'),
        ),
    ]
